/**
 * Build the deployable browser bundle from the style source of truth.
 * ====================================================================
 *   lib/styles.css            ← 样式唯一源（手动调整这里）
 *   lib/client.template.js    ← 应用逻辑模板（含 __PLUGIN_CSS__ 占位）
 *     ↓  npm run build  (node scripts/build-client.mjs)
 *   lib/client.js             ← 部署产物（GENERATED，勿手改）
 *
 * 改样式流程：编辑 lib/styles.css → npm run build → 重启 web
 * （link: 部署下无需重装依赖；file: 部署需 pnpm install --force）
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Escape CSS as the content of a double-quoted JS string literal (matches the original inline format). */
function escapeJsString(css) {
  return css
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, '\\n')
}

// Strip a UTF-8 BOM defensively (Windows editors may add one).
const css = readFileSync(join(root, 'lib', 'styles.css'), 'utf8').replace(/^\uFEFF/, '')
const template = readFileSync(join(root, 'lib', 'client.template.js'), 'utf8')

const PLACEHOLDER = '__PLUGIN_CSS__'
const occurrences = template.split(PLACEHOLDER).length - 1
if (occurrences !== 1) {
  throw new Error(
    `lib/client.template.js must contain exactly one ${PLACEHOLDER} placeholder (found ${occurrences}); `
    + 'do not write the token in comments',
  )
}

const banner = [
  '// GENERATED by scripts/build-client.mjs — DO NOT EDIT THIS FILE.',
  '// Edit lib/styles.css (styles) and lib/client.template.js (logic), then run: npm run build',
  '',
].join('\n')

const client = banner + template.replace(PLACEHOLDER, escapeJsString(css))
writeFileSync(join(root, 'lib', 'client.js'), client, 'utf8')
console.log(`lib/client.js regenerated (${Buffer.byteLength(client)} bytes)`)
